defmodule Quotechain.Repo.Migrations.CreateQuote do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quotes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quote_number, :text, null: false
      add :quote_obj, :decimal
      add :quote_date, :date
      add :account_reference, :text
      add :shipper_reference, :text
      add :service_type, :text
      add :service_type_description, :text
      add :consignment_type, :text
      add :consignment_type_desc, :text
      add :status_code, :text
      add :status_description, :text
      add :collection_instructions, :text
      add :delivery_instructions, :text
      add :estimated_kilometres, :bigint
      add :billable_units, :bigint
      add :rate_type, :text
      add :rate_type_description, :text
      add :total_quantity, :bigint
      add :total_weight, :decimal
      add :consignor_site, :text
      add :consignor_name, :text, null: false
      add :consignor_building, :text, null: false
      add :consignor_street, :text, null: false
      add :consignor_suburb, :text, null: false
      add :consignor_city, :text, null: false
      add :consignor_postal_code, :text, null: false
      add :consignor_contact_name, :text, null: false
      add :consignor_contact_tel, :text, null: false
      add :consignee_site, :text
      add :consignee_name, :text, null: false
      add :consignee_building, :text, null: false
      add :consignee_street, :text, null: false
      add :consignee_suburb, :text, null: false
      add :consignee_city, :text, null: false
      add :consignee_postal_code, :text, null: false
      add :consignee_contact_name, :text, null: false
      add :consignee_contact_tel, :text, null: false
      add :waybill_number, :text
      add :collection_reference, :text
      add :accepted_by, :text
      add :reject_reason, :text
      add :order_number, :text
      add :value_declared, :decimal
      add :charged_amount, :decimal
      add :cash_account_type, :text
      add :paying_party, :text
      add :vehicle_category, :text
      add :item, :map
      add :sundry, :map
    end
  end

  def down do
    drop table(:quotes)
  end
end
